baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Test site for mod-bootstrap'

[markup.goldmark.renderer]
unsafe = true

[module]
  workspace = "mod-bootstrap.work"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.imports]]
    path = "github.com/gethinode/mod-bootstrap"
  [[module.imports.mounts]]
    source = "assets/scss/modules/bootstrap/_vendor"
    target = "assets/scss/modules/bootstrap/vendor"
  [[module.imports.mounts]]
    source = "assets"
    target = "assets"
    excludeFiles = "scss/modules/bootstrap/_vendor/_rfs.scss"
