baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Test site for mod-bootstrap'

[markup.goldmark.renderer]
unsafe = true

[module]
  replacements = 'github.com/gethinode/mod-bootstrap -> ../..'
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.imports]]
    path = "github.com/gethinode/mod-bootstrap"
  # [[module.imports.mounts]]
  #   source = "assets/js/modules/bootstrap"
  #   target = "static/js"
  [[module.imports.mounts]]
    source = "assets/scss/modules/bootstrap/_vendor"
    target = "assets/scss/modules/bootstrap/vendor"
